@Api_URL = http://localhost:5173
@user_mail = "mail@mail.com"
@user_pass = "ElPasswordMasLargoPosible2026!"

### Create User
POST {{Api_URL}}/api/Auth/register/
Content-Type: application/json

{
  "email": {{user_mail}},
  "password": {{user_pass}}
}

### Login
POST {{Api_URL}}/api/Auth/login
Content-Type: application/json

{
  "email": {{user_mail}},
  "password": {{user_pass}}
}
