services:
  backend:
    image: reformas-backend:latest
    pull_policy: never
    container_name: reformas-api
    restart: unless-stopped
    ports:
      - "${API_PORT}:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Trust Server Certificate=true;SSL Mode=Prefer;Include Error Detail=true"
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      ApiSettings__BaseUrl: ${API_SETTINGS_BASE_URL}
      AllowedHosts: "*"
      Jwt__Issuer: "ReformasRapBackend"
      Jwt__Audience: "ReformasRapApp"
      Jwt__Key: ${JWT_SECRET_KEY}
      Resend__RESEND_API_KEY: ${RESEND_API_KEY}
    volumes:
      - aspnet-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - db_network
      - default

  frontend:
    image: reformas-frontend:latest
    pull_policy: never
    container_name: reformas-rap-app
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      BASE_URL: "http://localhost:${API_PORT}"
      STRAPI_API_URL: "http://backend:8080"
    depends_on:
      - backend

volumes:
  aspnet-keys:

networks:
  db_network:
    external: true
