# ====== Build stage ======
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src


COPY *.csproj ./
RUN dotnet restore

COPY . ./

RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false


# ====== Runtime stage ======
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "ReformasRapBackend.dll"]